name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install required components
      run: sudo apt-get update && sudo apt-get install -y libantlr4-runtime-dev libstdc++-10-dev
    - name: run make in the VIPRA directory
      run: cd VIPRA && make generate_main && make compile
