name: dev

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "dev" ]
    paths-ignore: [ "docs/**" ]

jobs:
  run-lint:
    uses: ./.github/workflows/lint.yml
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
