name: Deploy Documentation

on:
  push:
    branches: [ dev ]
    
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .
      - name: VIPRA Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
