
name: Documentation

permissions:
  contents: write
  pages: write

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "docs/**" ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./doxyfile
          working-directory: .

      - name: VIPRA Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          keep_files: true
          enable_jekyll: true