name: Main

permissions:
  contents: write
  pages: write

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

jobs:
  run-lint:
    uses: ./.github/workflows/lint.yml
  
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Tests
        run: make testing JOBS=8

      - name: Run tests
        run: ./build/__tests__/vipra_tests